[env:bed]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7
  adafruit/Adafruit MPU6050@^2.2.6
build_flags =
  -DMQTT_MAX_PACKET_SIZE=1024
