[env:ankle]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7
  sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
  adafruit/Adafruit MPU6050@^2.2.6
build_flags =
  -DMQTT_MAX_PACKET_SIZE=1024
